Enchancement/def sort order
KQMATH/moodle-local_qtracker pull request #22
Opened 2021-03-16 22:04 UTC by davrikn

2021-04-11 18:36 UTC, andstor requested changes

2021-04-11 18:36 UTC, andstor commented on classes/output/questions_table.php
> +                'sortorder' => SORT_ASC,
@davrikn Shouldn't the **id** also be sorted by `SORT_DESC`? I think we want the questions with the highest id (newest) listed first.

2021-04-11 18:38 UTC, andstor commented
Also @davrikn, did you test if it is still possible to change/override the default sorting by clicking on the column headers?

2021-04-12 18:50 UTC, davrikn commented
Ah, i assumed table-sorting was done with JS, added check for user override and the bug is solved

2021-06-11 08:35 UTC, merged